---
title: "R Notebook"
output: html_notebook
---

```{r}
set.seed(1234)
library(dplyr)
library(ggplot2)
library(lfboot)
library(purrr)
library(tidyr)
```
Here are some helper visualizations used in this script but unlikely to be
generally useful.

```{r}
align_to_list <- function(Zb, df = F, tol = 0.05) {
  procrustes(Zb, tol = tol) %>%
    .[["x_align"]] %>%
    arr_to_list(df = df)
}

align_with_truth <- function(ud_hats, U, Sigma, tol = 0.05) {
  c(ud_hats, list(U %*% diag(sqrt(Sigma)))) %>%
    align_to_list(tol = tol, df = T) %>%
    bind_rows(.id = "b") %>%
    group_by(b) %>%
    mutate(i = row_number()) %>%
    ungroup() %>%
    mutate(b = as.integer(b))
}
```


```{r}
B <- 1000
N <- 200
D <- 50
K <- 2
U <- r_ortho(N, D)
V <- r_ortho(D, D)
Sigma <- c(rep(10, 2), rep(0.01, D - K))
X <- U %*% diag(Sigma) %*% t(V) + rmat(N, D, 0.01)
```


```{r}
n_rep <- 500
coverage_rates <- matrix(0, n_rep, 3)

for (i in seq_len(n_rep)) {
  # extract once
  f <- features(X)
  boot_fun <- param_boot(f(X), K)
  ud_hats <- rerun(B, boot_fun()$ub) %>%
    align_to_list(df = F)
  ud_combined <- align_with_truth(ud_hats, U, Sigma)
  
  contained <- coverage(ud_combined %>% filter(b < B + 1),  ud_combined %>% filter(b == B + 1))
  coverage_rates[i, 1] <- mean(contained)
  
  # extract B times
  Zb <- rerun(B, f(X))
  ud_hats <- align_to_list(Zb)
  ud_combined <- align_with_truth(ud_hats, U, Sigma)

  contained <- coverage(ud_combined %>% filter(b < B + 1),  ud_combined %>% filter(b == B + 1))
  coverage_rates[i, 2] <- mean(contained)
  
  # compromise
  Zb <- rerun(10, f(X))
  boot_fun <- param_boot_ft(Zb, K)
  ud_hats <- rerun(B, boot_fun()$ub) %>%
    align_to_list()
  ud_combined <- align_with_truth(ud_hats, U, Sigma)
  contained <- coverage(ud_combined %>% filter(b < B + 1),  ud_combined %>% filter(b == B + 1))
  coverage_rates[i, 3] <- mean(contained)
}
```


```{r}
coverage_rates2 <- data.frame(coverage_rates) %>%
  set_names(c("single", "repeat", "compromise")) %>%
  pivot_longer(single:compromise, names_to = "method", values_to = "coverage")
ggplot(coverage_rates2, aes(method, y = coverage)) +
  geom_hline(yintercept = 0.95, col = "red") +
  geom_point(position = position_dodge2(w = .1))
```
