---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)
library(purrr)
source("../R/simulation.R")
source("../R/stability.R")
```

```{r}
B <- 1000
N <- 200
D <- 50
K <- 2
U <- r_ortho(N, D)
V <- r_ortho(D, D)
Sigma <- c(rep(10, 2), rep(0.01, D - K))
X <- U %*% diag(Sigma) %*% t(V) + rmat(N, D, 0.01)

features <- function(X, K = 2, sigma_e = 0.1) {
  N <- nrow(X)
  D <- nrow(X)
  svx <- svd(X)
  
  function(X) {
    Pi <- random_permutation(K)
    (X %*% svx$v[, 1:K] %*% diag(sqrt(svx$d[1:K])) + rmat(N, K, sigma_e)) %*% Pi
  }
}
```

Here is the strategy that extracts the features once and then applies a
parametric bootstrap according to the assumed model.

```{r}
f <- features(X)
Z <- f(X)
svz <- svd(Z)
```

```{r}
param_boot <- function(u_hat, d_hat, E) {
  eB <- matrix(sample(E, replace = TRUE), nrow(E), ncol(E))
  Pi <- random_permutation(ncol(E))
  Zb <- (u_hat %*% diag(sqrt(d_hat)) + eB) %*% Pi
  list(Zb = Zb, ub = svd(Zb)$u %*% diag(sqrt(svd(Zb)$d)))
}

arr_to_list <- function(x, df = F) {
  if (df) {
    res <- map(1:dim(x)[3], ~ data.frame(x[,, .]))
  } else {
    res <- map(1:dim(x)[3], ~ x[,, .])
  }
  
  res
}

u_hat <- svz$u[, 1:K]
d_hat <- svz$d[1:K]
E <- Z - u_hat %*% diag(sqrt(d_hat))

ud_hats <- rerun(B, param_boot(u_hat, d_hat, E)$ub) %>%
  procrustes() %>%
  .[["x_align"]] %>%
  arr_to_list(df = F)

ud_combined <- c(ud_hats, list(U %*% diag(sqrt(Sigma)))) %>%
  procrustes() %>%
  .[["x_align"]] %>%
  arr_to_list(df = T) %>%
  bind_rows(.id = "b") %>%
  group_by(b) %>%
  mutate(i = row_number()) %>%
  ungroup() %>%
  mutate(b = as.integer(b))
```

```{r}
ggplot(ud_combined %>% filter(i < 10, b < B + 1), aes(X1, X2)) +
  geom_point(alpha = 0.4, size = 0.2) +
  geom_point(data = ud_combined %>% filter(i < 10, b == B + 1), size = 1, shape = 15, col = "red") +
  facet_wrap(~ i, scale = "free")

ggplot(ud_combined %>% filter(b < B + 1), aes(X1, X2)) +
  geom_point(alpha = 0.4, size = 0.2) +
  geom_point(data = ud_combined %>% filter(b == B + 1), size = 1, shape = 15, col = "red")

ggplot(ud_combined %>% filter(b < 101), aes(X1, X2)) +
  geom_point(alpha = 0.4, size = 0.2) +
  geom_point(data = ud_combined %>% filter(b == B + 1), size = 1, shape = 15, col = "red") +
  xlim(-0.001, 0.001) +
  ylim(-0.001, 0.001)
```

What if we instead extract $B$ sets of features?

```{r}
f <- features(X)
Zb <- rerun(B, f(X))

ud_hats <- Zb %>%
  procrustes() %>%
  .[["x_align"]] %>%
  arr_to_list(df = F)

ud_combined <- c(ud_hats, list(U %*% diag(sqrt(Sigma)))) %>%
  procrustes() %>%
  .[["x_align"]] %>%
  arr_to_list(df = T) %>%
  bind_rows(.id = "b") %>%
  group_by(b) %>%
  mutate(i = row_number()) %>%
  ungroup() %>%
  mutate(b = as.integer(b))
```


```{r}
ggplot(ud_combined %>% filter(i < 10, b < B + 1), aes(X1, X2)) +
  geom_point(alpha = 0.4, size = 0.2) +
  geom_point(data = ud_combined %>% filter(i < 10, b == B + 1), size = 1, shape = 15, col = "red") +
  facet_wrap(~ i, scale = "free")

ggplot(ud_combined, aes(X1, X2)) +
  geom_point(alpha = 0.4, size = 0.2) +
  geom_point(data = ud_combined %>% filter(b == B + 1), size = 1, shape = 15, col = "red")
```

```{r}
param_boot2 <- function(u_hat, d_hat, Eb) {
  Estar <- do.call(cbind, Eb)
  K <- length(d_hat)
  Estar <- as.matrix(Estar[, sample(ncol(Estar), K, replace = T)])
  Pi <- random_permutation(K)
  Zb <- (u_hat %*% diag(sqrt(d_hat)) + Estar) %*% Pi
  list(Zb = Zb, ub = svd(Zb)$u %*% diag(sqrt(svd(Zb)$d)))
}

f <- features(X)
Zb <- rerun(10, f(X))

ud_hats <- Zb %>%
  procrustes() %>%
  .[["x_align"]] %>%
  apply(c(1, 2), mean)

svz <- svd(ud_hats)
u_hat <- svz$u[, 1:K]
d_hat <- svz$d[1:K]
Eb <- map(Zb, ~ . - u_hat %*% diag(sqrt(d_hat)))

ud_hats <- rerun(B, param_boot2(u_hat, d_hat, Eb)$ub) %>%
  procrustes() %>%
  .[["x_align"]] %>%
  arr_to_list(df = F)

ud_combined <- c(ud_hats, list(U %*% diag(sqrt(Sigma)))) %>%
  procrustes() %>%
  .[["x_align"]] %>%
  arr_to_list(df = T) %>%
  bind_rows(.id = "b") %>%
  group_by(b) %>%
  mutate(i = row_number()) %>%
  ungroup() %>%
  mutate(b = as.integer(b))
```


```{r}
ggplot(ud_combined %>% filter(i < 10, b < B + 1), aes(X1, X2)) +
  geom_point(alpha = 0.4, size = 0.2) +
  geom_point(data = ud_combined %>% filter(i < 10, b == B + 1), size = 1, shape = 15, col = "red") +
  facet_wrap(~ i, scale = "free")
```

