---
title: "R Notebook"
output: html_notebook
---

```{r}
set.seed(123)
library(dplyr)
library(ggplot2)
library(purrr)
library(lfboot)
library(abind)
```


```{r}
align_to_list <- function(Zb, df = F, tol = 0.05) {
  procrustes(Zb, tol = tol) %>%
    .[["x_align"]] %>%
    arr_to_list(df = df)
}

align_with_truth <- function(ud_hats, U, Sigma, tol = 0.05) {
  tmp <- c(ud_hats, list(U %*% diag(sqrt(Sigma)))) %>%
    align_to_list(tol = tol, df = T) %>%
    bind_rows(.id = "b") %>%
    group_by(b) %>%
    mutate(i = row_number()) %>%
    ungroup() %>%
    mutate(b = as.integer(b))
}
```

```{r}
B <- 1000
N <- 200
D <- 50
K <- 2
U <- r_ortho(N, D)
V <- r_ortho(D, D)
Sigma <- c(rep(10, 2), rep(0.01, D - K))
X <- U %*% diag(Sigma) %*% t(V) + rmat(N, D, 0.01)
beta <- c(c(1, -1), rep(0, D - K))
y <- U %*% diag(sqrt(Sigma)) %*% beta + rnorm(N, 0, 0.1)
```

```{r}
plot(U[, 1] * sqrt(Sigma[1]), y)
```

```{r}
ix <- sample(N, N / 2)
f <- features(X[ix, ])
#Zb <- rerun(B, f(X))
#ud_hats <- align_to_list(Zb)
#ud_combined <- align_with_truth(ud_hats, U, Sigma)
```

```{r}
Zb <- rerun(1000, f(X[-ix, ])) %>%
  align_to_list()
plot(Zb[[1]][, 1], Zb[[9]][, 1])
```


```{r}
beta_hats <- map(1:length(Zb), ~ lm(y[-ix] ~ -1 + Zb[[.]])) %>%
  map_dfr(~ coef(.)) %>%
  set_names(c("u1", "u2"))
```


```{r}
ggplot(beta_hats) +
  geom_histogram(aes(u1))
ggplot(beta_hats) +
  geom_histogram(aes(u2))
```

```{r}
feature_angles <- function(z_hat, U, Sigma, K = 2) {
  t(z_hat) %*% (U[, 1:K] %*% diag(sqrt(Sigma[1:K])))
}
```


```{r}
Z_bar <- Zb %>%
  abind(along = 3) %>%
  apply(c(1, 2), mean)

true_scores <- feature_angles(Z_bar, U[-ix, ], Sigma) %*% beta[1:K]
svz <- svd(Z_bar)
boot_angles <- map(Zb, ~ feature_angles(., svz$u, svz$d))
boot_scores <- map(seq_along(Zb), ~ boot_angles[[.]] %*% unlist(beta_hats[., ])) %>%
  map_dfr(~ data.frame(t(.)), .id = "b")
```

```{r}
true_scores
ggplot(boot_scores) +
  geom_histogram(aes(x = X1)) +
  geom_vline(xintercept = -true_scores[1], col = "red")
ggplot(boot_scores) +
  geom_histogram(aes(x = X2)) +
  geom_vline(xintercept = -true_scores[2], col = "red")
```

