---
title: "R Notebook"
output: html_notebook
params:
  data_dir: "/Users/kris/Documents/figs/figures/"
---

```{r}
library("dplyr")
library("ggplot2")
library("purrr")
library("readr")
library("stringr")
theme_set(theme_bw())
```


```{r fig.width = 6, fig.height = 4}
selections <- dir(params$data_dir, "selections", full = TRUE, recursive = TRUE) %>%
  map_dfr(~ read_csv(., col_types = cols())) %>%
  mutate(
    Reduction = ifelse(sca, "SCA", "SVD")
  )
selections$split <- factor(selections$split, levels = c("train", "dev", "test"))

ggplot(selections) +
  #geom_errorbar(
  #  aes(x = pi_thr, ymin = min, ymax = max, col = sca),
  #  size = 0.3, alpha = 0.6
  #) +
  geom_line(
    aes(x = pi_thr, y = median, col = split, linetype = Reduction),
    size = 0.7, alpha = 0.8
    ) +
  facet_grid(model ~ train_perc) +
  ylim(0, 8) +
  labs(
    x = expression(pi[thr]),
    y = expression("|" ~ S(pi[thr]) ~ "| when " ~ lambda ~ " = 0.83 ")
  ) +
  scale_color_brewer(palette = "Set2") +
  scale_x_continuous(breaks = c(0.5, 0.8)) +
  scale_y_continuous(breaks = c(1, 4, 7)) +
  theme(
    panel.spacing.x = unit(0, "cm"),
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(angle = 90),
    legend.position = "bottom"
  )

#ggsave("~/Desktop/conceptual/learned_inference/notes/figure/selection_summary2.png", dpi = 350)
```

```{r}
cca_paths <- dir(params$data_dir, "cca", recursive = TRUE, full = TRUE)
cca_data <- cca_paths %>%
  map_dfr(~ read_csv(., col_types = cols()), .id = "path") %>%
  mutate(path = cca_paths[as.numeric(path)])
```

```{r}
cca_data <- cca_data %>%
  mutate(
    train_perc = as.integer(str_extract(path, "[0-9]+")),
    method = str_extract(path, "cnn|vae|rcf"),
    reduction = str_extract(path, "sca|svd")
  )
```

```{r, fig.height = 5, fig.width = 8}
cca_data$split <- factor(cca_data$split, levels = c("train", "dev", "test"))
cca_data$train_perc <- as.factor(cca_data$train_perc)
ggplot(cca_data) +
  geom_point(
    aes(x = interaction(train_perc, reduction), y = rho, col = split),
    size = 1, alpha = 0.5,
    position = position_jitter(w = 0.2)
  ) +
  labs(
    y = expression("Canonical Correlation " ~ rho[k]),
    x = "Canonical Correlation Analysis Dimension"
  ) +
  scale_color_brewer(palette = "Set2") +
  facet_grid(method ~ k) +
  theme(
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(angle = 90),
    axis.ticks.y = element_blank(),
    axis.text.y = element_text(size = 7),
    legend.position = "bottom",
    panel.spacing.x = unit(0, "cm")
  ) +
  guides(color = guide_legend(override.aes = list(size = 3, alpha = 1))) +
  ylim(0, 1)
```
```{r}
cca_data$path %>% unique()
```


```{r, fig.width = 4, fig.height = 3}
fss <- dir(file.path(params$data_dir, "ftotal"), "feature", full = TRUE, recursive = TRUE) %>%
  map_dfr(~ read_csv(., col_types = cols())) %>%
  mutate(
    train_perc = as.factor(str_extract(model, "[0-9]+")),
    method = str_extract(model, "cnn|vae|rcf"),
    Reduction = ifelse(sca, "SCA", "SVD")
  )


ggplot(fss) +
  geom_point(aes(x = train_perc, col = Reduction, y = feature_stability / 10)) + # 10 reduction dimensions
  scale_y_log10() +
  facet_grid(. ~ method) +
  labs(
    x ="% Data used for Feature Learning",
    y = "Feature Subspace Instability"
  ) +
  scale_color_manual(values = c("#cd5c5c", "#5ccdcd")) +
  theme(
    panel.spacing = unit(0, "cm"),
    legend.position = "bottom"
  )
```

