---
title: "visualize_pi_hat"
output: html_notebook
params:
  output_path: "/Users/kris/Downloads/figs/tnbc/"
---

```{r}
library("dplyr")
library("ggplot2")
library("inference")
library("purrr")
library("readr")
library("stringr")
theme_set(theme_bw())
dpath <- function(s, d=params$output_path) {
  file.path(d, s)
}
```

```{r}
#' Helper function for plotting \hat{Pi}
plot_curves <- function(pi_hat, sca_bit, perc=NULL) {
  ggplot(pi_hat %>% filter(j > 0, sca == sca_bit)) +
    geom_line(
      aes(x = log(lambda), 
          y = value, 
          col = split, 
          group = jb),
      alpha = 0.5
      ) +
    scale_color_brewer(palette = "Set2") +
    scale_x_reverse() +
    labs(
      x = expression(log(lambda)),
      y = expression(hat(Pi)^{b}~(lambda))
    ) +
    guides(color = guide_legend(override.aes = list(size = 4, alpha = 1))) +
    scale_y_continuous(breaks = c(0.1, 0.5, 0.9)) +
    facet_grid(method ~ j) +
    theme(
      legend.position = "bottom",
      panel.grid.minor = element_blank(),
      panel.spacing.x = unit(0, "cm")
    ) +
    #ggtitle(sprintf("%s%% Learning Split, %s", perc, ifelse(sca_bit, "SCA", "PCA")))
    ggtitle(sprintf("TNBC Stability Curves, %s", ifelse(sca_bit, "SCA", "PCA")))
}
```

```{r}
paths <- dir(params$output_path, "pi_hat*", recursive = TRUE) %>%
  dpath()
pi_hat <- map_dfr(paths, read_csv, col_types = cols(), .id = "path")
```

```{r}
pi_hat$path <- as.integer(pi_hat$path)
pi_hat$sca <- grepl("sca", paths)[pi_hat$path]
pi_hat$method <- str_extract(paths, "cnn|rcf|vae")[pi_hat$path] %>%
  toupper()
pi_hat$train_perc <- str_extract(paths, "15|50|90")[pi_hat$path]
pi_hat$split <- factor(pi_hat$split, levels = c("train", "dev", "test"))
```

```{r}
p <- list()
i <- 1
for (sca in c(TRUE, FALSE)) {
#  for (train_perc in c(15, 50, 90)) {
    p[[i]] <- plot_curves(pi_hat, sca, train_perc)
    i <- i + 1
#  }
}
```

```{r, fig.height = 4, fig.width = 12}
for (i in seq_along(p)) {
  ggsave(
    sprintf("~/Desktop/conceptual/learned_inference/notes/figure/tnbc_selection_paths-%s.png", i), 
    p[[i]],
    dpi = 350,
    height = 4,
    width = 12
  )
}
```

