bootstrap:
  B: 20
  path: bootstraps/vae_boot/bootstraps.csv
organization:
  features_dir: features/vae_coreset_1000
  out_dir: runs/vae_coreset_1000
  train_dir: train
  xy: Xy.csv
train:
  batch_size: 32
  checkpoint: runs/vae_no_boot/None/model_final.pt
  lr: 0.001
  n_epochs: 1000
  save_every: 1000
  z_dim: 64
