---
title: Data Generation Mechanism
---

```{r}
library("ggplot2")
library("sf")
library("raster")
library("stars")
source("sim/point_process.R")
knitr::opts_knit$set(root.dir = Sys.getenv(c("ROOT_DIR")))

theme_set(theme_bw() + theme(panel.grid=element_blank()))
scale_x_continuous <- function(...) {
  ggplot2::scale_x_continuous(..., expand = c(0, 0))
}
scale_y_continuous <- function(...) {
  ggplot2::scale_y_continuous(..., expand = c(0, 0))
}
scale_fill_continuous <- function(...) {
  ggplot2::scale_fill_continuous(..., low="white", high="black")
}
```

First, we'll show how to simulate a single image.

```{r}
x <- expand.grid(seq(0.1, 1, 0.05), seq(0.1, 1, 0.05))
intensity <- matern_process(x)
z <- inhomogeneous_process(1000, intensity)
ggplot() +
  geom_tile(aes(x = Var1, y = Var2, fill = z), intensity) +
  geom_point(mapping = aes(x = X1, y = X2), data.frame(z), col = "red") +
  coord_fixed()
```

```{r}
library("igraph")
library("stars")
library("spdep")
nb_knn <- knn2nb(knearneigh(coords, k = 5))
plot(nb_knn, coords)

library("IsingSampler")
n <- 20
W <- -exp(-dist(z)) %>%
  as.matrix()
W[W < .6] <- 0
diag(W) <- 0

img_df <- data.frame(
  z1 = z[, 1],
  z2 = z[, 2],
  label = res[1, ]
)

ggplot(img_df) +
  geom_point(
    aes(
      x = z1, y = z2, col = label
    )
  )

```
