---
title: Recovery ability
---

```{r}
library("ggplot2")
library("readr")
library("dplyr")
library("stringr")
library("png")
library("glmnet")
```

Load the previously extracted features.
```{r}
conf <- yaml.load_file("conf/train.yaml")

z <- read_csv(conf$features_dir) %>%
  select(-X1) %>%
  select(path, y, everything())
z$ix <- str_extract(z$path, "[0-9]+") %>%
  as.integer()

y <- z$y
x <- z %>%
  select(matches("[0-9]+")) %>%
  as.matrix()

plot(z[[13]], y)
hist(cor(x, y), 20)

cv_res <- cv.glmnet(as.matrix(x), scale(y))
plot(cv_res)

fit <- glmnet(as.matrix(x), scale(y))
plot(fit)
image(coef(fit))

plot(y, predict(fit, newx = as.matrix(x))[, 73], asp = 1, ylab="y_hat")
order(coef(fit)[, 10], decreasing = TRUE)
plot(x[, 40], y, asp = 1)
```

Get paths to all the original images, and build an MDS from the learned features.
```{r}
png_paths <- gsub("npy", "png", z$path)
png_paths <- gsub("train", "pngs", png_paths)
png_paths <- paste0("../", png_paths)

ims <- lapply(png_paths, readPNG)
coords <- cmdscale(dist(x))
plot(coords)
```

Plot images along the MDS coordinates.
```{r}
xgrid <- seq(-4, 4.5, by=0.5)
xgrid <- expand.grid(xgrid, xgrid)

plot_data <- list()
for (i in seq_len(nrow(xgrid))) {
  cur_dist <- proxy::dist(xgrid[i, ], coords)
  if (min(cur_dist) < 0.2) {
    im <- ims[[which.min(cur_dist)]]
  } else {
    im <- NULL
  }

  plot_data[[i]] <- list(
    x = xgrid[i, 1],
    y = xgrid[i, 2],
    im = im
  )
}

height <- 2.4
width <- 2.4

plot(xgrid, t="n", asp = 1)
for (i in seq_len(nrow(xgrid))){
  if (is.null(plot_data[[i]]$im)) next

  rasterImage(
    plot_data[[i]]$im,
    xleft = plot_data[[i]]$x - 0.1 * width,
    ybottom = plot_data[[i]]$y - 0.1 * height,
    xright = plot_data[[i]]$x + 0.1 * width,
    ytop = plot_data[[i]]$y + 0.1 * height,
    interpolate = FALSE
  )
}
```
