organization: # all relative to $DATA_DIR
  features_dir: "cnn15/features/"
  metadata: "cnn15/metadata.csv"
  model: "cnn15/model_best.pt"
  splits: "splits_0.15-train.csv"
  xy: "Xy.csv"
train:
  model: "cnn"
  checkpoint: null
  batch_size: 128
  lr: 0.0001
  n_epochs: 240
  save_every: 80
  save_subset: 2000
bootstrap:
  path: "bootstraps_0.15-train.csv"
  index: null
  B: 20
