organization: # all relative to $DATA_DIR
  features_dir: "cnn50/features/"
  metadata: "cnn50/metadata.csv"
  model: "cnn50/model_best.pt"
  splits: "splits_0.5-train.csv"
  xy: "Xy.csv"
train:
  batch_size: 128
  checkpoint: null
  factor: 0.5
  lr: 0.0001
  model: "cnn"
  momentum: 0.9
  n_epochs: 100
  p_in: 3
  patience: 5
  save_every: 50
  save_subset: 2000
bootstrap:
  path: "bootstraps_0.5-train.csv"
