organization: # all relative to $DATA_DIR
  features_dir: "cnn50/features/"
  metadata: "cnn50/metadata.csv"
  model: "cnn50/model_best.pt"
  splits: "splits_0.5-train.csv"
  xy: "Xy.csv"
train:
  model: "cnn"
  checkpoint: null
  batch_size: 128
  lr: 0.0001
  n_epochs: 25
  save_every: 50
  save_subset: 2000
bootstrap:
  path: "bootstraps_0.5-train.csv"
  index: null
  B: 20
