organization: # all relative to $DATA_DIR
  features_dir: "cnn90/features/"
  metadata: "cnn90/metadata.csv"
  model: "cnn90/model_best.pt"
  splits: "splits_0.9-train.csv"
  xy: "Xy.csv"
train:
  batch_size: 128
  checkpoint: null
  lr: 0.001
  momentum: 0.9
  model: "cnn"
  n_epochs: 30
  p_in: 3
  save_every: 10
  save_subset: 2000
bootstrap:
  path: "bootstraps_0.9-train.csv"
