organization: # all relative to $DATA_DIR
  features_dir: "tnbc/features/"
  model: "tnbc/model_best.pt"
  xy: "tnbc/split.csv"
  metadata: "tnbc/layers.csv"
train:
  model: "cnn"
  checkpoint: null
  batch_size: 128
  lr: 0.00005
  n_epochs: 30
  save_every: 10
  save_subset: 2000
bootstrap:
  path: "bootstraps_0.9-train.csv"
  index: null
  B: 20
