organization: # all relative to $DATA_DIR
  features_dir: "tnbc_cnn/features/"
  model: "tnbc_cnn/model_best.pt"
  xy: "Xy.csv"
  splits: "Xy.csv"
  metadata: "tnbc_cnn/metadata.csv"
train:
  batch_size: 64
  checkpoint: null
  factor: 0.5
  lr: 0.0001
  model: "cnn"
  momentum: 0.9
  n_epochs: 100
  p_in: 7
  patience: 5
  save_every: 50
  save_subset: 2000
bootstrap:
  path: "bootstraps.csv"
