organization: # all relative to $DATA_DIR
  features_dir: "features/"
  model: "model_best.pt"
  xy: "split.csv"
  splits: "split.csv"
  metadata: "layers.csv"
train:
  batch_size: 128
  checkpoint: null
  lr: 0.00005
  model: "cnn"
  n_epochs: 30
  p_in: 7
  save_every: 10
  save_subset: 2000
bootstrap:
  path: "bootstraps.csv"
