organization: # all relative to $DATA_DIR
  features_dir: "features/vae_20200724/features.csv"
  out_dir: "runs/vae_20200729/"
  train_dir: "train"
  xy: "Xy.csv"
train:
  checkpoint: null
  batch_size: 32
  lr: 0.001
  n_epochs: 75
  save_every: 10
  z_dim: 64
bootstrap:
  path: "bootstraps/vae_20200729/bootstraps.csv"
  index: null
  B: 20
