organization: # all relative to $DATA_DIR
  features_dir: "vae/features/"
  metadata: "vae/metadata.csv"
  splits: "splits.csv"
  xy: "Xy.csv"
train:
  checkpoint: null
  batch_size: 128
  lr: 0.0001
  n_epochs: 25
  save_every: 5
  z_dim: 64
bootstrap:
  path: "bootstraps.csv"
  index: null
  B: 20
