organization: # all relative to $DATA_DIR
  features_dir: "cnn/features/"
  metadata: "cnn/metadata.csv"
  model: "cnn/model_best.pt"
  splits: "splits.csv"
  xy: "Xy.csv"
train:
  model: "cnn"
  checkpoint: null
  batch_size: 128
  lr: 0.0001
  n_epochs: 25
  save_every: 50
  save_subset: 2000
bootstrap:
  path: "bootstraps.csv"
  index: null
  B: 20
