organization:
  features_dir: features/vae_boot
  out_dir: runs/vae_boot
  train_dir: train
  xy: Xy.csv
train:
  batch_size: 32
  checkpoint: null
  lr: 0.001
  n_epochs: 1
  save_every: 1
  z_dim: 64
bootstrap:
  B: 50
  path: bootstraps/vae_boot/bootstraps.csv
