organization:
  features_dir: "features/vae_no_boot/"
  out_dir: "runs/vae_no_boot/"
  train_dir: "train"
  xy: "Xy.csv"
train:
  checkpoint: null
  batch_size: 32
  lr: 0.001
  n_epochs: 100
  save_every: 10
  z_dim: 64
bootstrap:
  path: null
  B: null
