organization: # all relative to $DATA_DIR
  features_dir: "vae15/features/"
  metadata: "vae15/metadata.csv"
  model: "vae15/model_best.pt"
  splits: "splits_0.15-train.csv"
  xy: "Xy.csv"
train:
  batch_size: 128
  checkpoint: null
  lr: 0.001
  model: "vae"
  momentum: 0.9
  n_epochs: 480
  save_every: 80
  save_subset: 2000
  z_dim: 64
bootstrap:
  path: "bootstraps_0.15-train.csv"
  index: null
  B: 20
