organization: # all relative to $DATA_DIR
  features_dir: "vae50/features/"
  metadata: "vae50/metadata.csv"
  model: "vae50/model_best.pt"
  splits: "splits_0.5-train.csv"
  xy: "Xy.csv"
train:
  model: "vae"
  checkpoint: null
  batch_size: 128
  lr: 0.0001
  n_epochs: 60
  save_every: 20
  save_subset: 2000
  z_dim: 64
bootstrap:
  path: "bootstraps_0.5-train.csv"
  index: null
  B: 20
