organization: # all relative to $DATA_DIR
  features_dir: "vae50/features/"
  metadata: "vae50/metadata.csv"
  model: "vae50/model_best.pt"
  splits: "splits_0.5-train.csv"
  xy: "Xy.csv"
train:
  batch_size: 128
  checkpoint: null
  lr: 0.001
  model: "vae"
  momentum: 0.9
  n_epochs: 120
  save_every: 20
  save_subset: 2000
  z_dim: 64
bootstrap:
  path: "bootstraps_0.5-train.csv"
  index: null
  B: 20
