organization: # all relative to $DATA_DIR
  features_dir: "vae90/features/"
  metadata: "vae90/metadata.csv"
  model: "vae90/model_best.pt"
  splits: "splits_0.9-train.csv"
  xy: "Xy.csv"
train:
  batch_size: 128
  checkpoint: null
  lr: 0.001
  model: "vae"
  momentum: 0.9
  n_epochs: 60
  save_every: 10
  save_subset: 2000
  z_dim: 64
bootstrap:
  path: "bootstraps_0.9-train.csv"
  index: null
  B: 20
