bootstrap:
  B: 50
  path: bootstraps/vae_boot/bootstraps.csv
organization:
  features_dir: features/vae_tune_80
  out_dir: runs/vae_tune_80
  train_dir: train
  xy: Xy.csv
train:
  batch_size: 32
  checkpoint: runs/vae_no_boot/None/model_80.pt
  lr: 0.001
  n_epochs: 19
  save_every: 1000
  z_dim: 64
