bootstrap:
  B: 20
  index: null
  path: bootstraps/vae_20200802/bootstraps.csv
organization:
  features_dir: features/vae_20200802/
  out_dir: runs/vae_tune_30
  train_dir: train
  xy: Xy.csv
train:
  batch_size: 32
  checkpoint: runs/vae_no_boot/None/model_{start_epoch}.pt
  lr: 0.001
  n_epochs: 44
  save_every: 5
  z_dim: 64
