organization: # all relative to $DATA_DIR
  features_dir: "features/vae_20200802/"
  out_dir: "runs/vae_20200802/"
  train_dir: "train"
  xy: "Xy.csv"
train:
  checkpoint: "runs/vae_no_boot/model_10.pt"
  batch_size: 32
  lr: 0.001
  n_epochs: 65
  save_every: 5
  z_dim: 64
bootstrap:
  path: "bootstraps/vae_20200802/bootstraps.csv"
  index: null
  B: 20
