bootstrap:
  B: 5
  path: bootstraps/vae_boot/bootstraps.csv
organization:
  features_dir: features/vae_tune_40
  out_dir: runs/vae_tune_40
  train_dir: train
  xy: Xy.csv
train:
  batch_size: 32
  checkpoint: runs/vae_no_boot/None/model_40.pt
  lr: 0.001
  n_epochs: 34
  save_every: 1000
  z_dim: 64
